[package]
name = "proc_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "*"
proc-macro2 = "*"
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }
